# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Product.create( :name => "Bag_Stand_Nike_V4",  :description => "This bag is ultra-lightweight and durable construction. It provides ultimate confort for walking. With six functional pockets, five of which are zippered, you get specialized storage options.",  :prd_type => "Bag-Stand",  :brand => "Nike",  :color => "Blue",  :price => "149.99",  :image_url => "Golf_bag_Nike_Stand_black_bleu.jpeg",  :feature1 => "8.5' top",  :feature2 => "Five-way, two full dividers, putter well",  :feature3 => "6 pockets")
Product.create( :name => "Bag_Stand_NK_AIRxxx",  :description => "Sporting technology designed with the ultimate comfort in mind for the course walker, this bag features Nike Equaflex Max Air curved, revolving, double-strap system and a ventilated air mesh back pad. Nine functional pockets.",  :prd_type => "Bag-Stand",  :brand => "Nike",  :color => "Blue",  :price => "169.99",  :image_url => "Golf_Bag_Stand_Nike_AIRxxx.jpeg",  :feature1 => "8.5' top",  :feature2 => "Eight-way, three divider",  :feature3 => "9 pockets")
Product.create( :name => "Bag_Stand_TM_PStand4.0",  :description => "The TaylorMade Pro Stand 4.0 comes with a five-way top (8.5' x 9.5') that includes a dual shoulder strap system.",  :prd_type => "Bag-Stand",  :brand => "TaylorMade",  :color => "White and Black",  :price => "149.99",  :image_url => "Golf_Bag_Stand_TaylorMade_PStand4.0.jpeg",  :feature1 => "9.5'  top",  :feature2 => "Five-way top",  :feature3 => "6 pockets")
Product.create( :name => "Bag_Stand_TT_X4.0",  :description => "The Tour Trek T 4.0 Stand Bag is a lightweight, yet durable option to keep you comfortable while walking the course. An 11-way top combined with 8 storage compartments organizes your clubs and gear for easy accessibility. With an extended leg span and a low profile design, the T 4.0 stand bag is stable on uneven terrain.",  :prd_type => "Bag-Stand",  :brand => "TourTrek",  :color => "Black, Grey, White",  :price => "169.99",  :image_url => "Golf_Bag_Stand_TourTrek_X4.0.jpeg",  :feature1 => "8.5' top",  :feature2 => "11-way",  :feature3 => "7 pockets")
Product.create( :name => "Bag_Stand_SM_XS-130",  :description => "Adapted from Sun Mountain’s best-selling C-130 cart bag, the Sun Mountain C-130S Stand Bag is designed primarily for cart use, with a stand system added for the range. Cart-friendly features include a leg-lock system, a cart strap tunnel which allows full pocket access when the bag is on a cart and a cart-friendly bottom that fits nicely in riding cart bag wells.",  :prd_type => "Bag-Stand",  :brand => "SunMountain",  :color => "Black and Orange",  :price => "289.99",  :image_url => "Golf_Bag_Stand_SunMountain_XS-130.jpeg",  :feature1 => "10.5'  top",  :feature2 => "14-way",  :feature3 => "8 pockets")
Product.create( :name => "Bag_Stand_NK_Type01",  :description => "Nike Sport IV Cart Bag has various specialized compartments to keep essential items easily accessible during your round. Made of durable, lightweight material, this bag helps protect your gear without weighing you down.",  :prd_type => "Bag-Cart",  :brand => "Nike",  :color => "Black",  :price => "149.99",  :image_url => "Golf_bag_Cart_Nike_Black.jpeg",  :feature1 => "9.5 ' top",  :feature2 => "14 individual tubes",  :feature3 => "9 pockets")
Product.create( :name => "Bag_Cart_TM_SuperV",  :description => "Golf_bag_Cart_Taylormade_SuperV",  :prd_type => "Bag-Cart",  :brand => "TaylorMade",  :color => "Red",  :price => "299.99",  :image_url => "Golf_bag_Cart_Taylormade_SuperV.jpeg",  :feature1 => "9.5 ' top",  :feature2 => "Durable construction.",  :feature3 => "10 pockets")
Product.create( :name => "Bag_Cart_TM_Clementine",  :description => "This 4.4 lbs. Cart Bag comes with a ten-way stadium top (10.5' x 9'), two different slots to accommodate oversized putter grips, two full-length dividers, and a single shoulder strap and carry handle. It is also push-cart compatible.",  :prd_type => "Bag-Cart",  :brand => "TaylorMade",  :color => "Grey",  :price => "179.99",  :image_url => "Golf_bag_Cart_TaylorMade_Clementine.jpeg",  :feature1 => "10.5 ' top",  :feature2 => "2 dividers",  :feature3 => "7 pockets")
Product.create( :name => "Bag_Cart_SM_XX-130",  :description => "Sun Mountain's best-selling cart bag, the C-130 Cart Bag was created to work optimally on a riding cart. All of the features are designed with cart use in mind, starting with the reverse-orientation top, the three utility handles integrated into the top, and the strap channel. Sun Mountain also added an integrated putter well and made sure all pockets are accessible when the bag is on a cart.",  :prd_type => "Bag-Cart",  :brand => "SunMountain",  :color => "Grey",  :price => "279.99",  :image_url => "Golf_Bag_Cart_SunMountain_XX-130.jpeg",  :feature1 => "10.5 ' top",  :feature2 => "14 individual tubes",  :feature3 => "9 pockets")
Product.create( :name => "Bag_Cart_SM_XXTour",  :description => "The Sun Mountain 2017 Tour Series Cart Bag is a full-sized, full-featured cart bag designed for riding and push cart use. The bag bottom is molded to fit securely over the lower bag rest of the Speed Cart and Micro-Cart Series carts and stands flat on riding carts. The Tour Series bags has a spacious, four-way top with full-length dividers that makes pulling clubs easy.",  :prd_type => "Bag-Cart",  :brand => "SunMountain",  :color => "Black",  :price => "359.99",  :image_url => "Golf_Bag_Cart_SunMountain_XXTour.jpeg",  :feature1 => "11' top",  :feature2 => "Roomy, four-way top",  :feature3 => "10 pockets")
